import { Platform } from 'react-native';

export const SUBSCRIPTIONS_PLANS_ANDROID = {
  YEARLY: '',
  MONTHLY: '',
  WEEKLY: '',
};

export const SUBSCRIPTIONS_PLANS_IOS = {
  YEARLY: '',
  MONTHLY: '',
  WEEKLY: '',
};

export const SUBSCRIPTION_PLANS_PER_PLATFORM = Platform.select({
  android: {
    YEARLY: SUBSCRIPTIONS_PLANS_ANDROID.YEARLY,
    MONTHLY: SUBSCRIPTIONS_PLANS_ANDROID.MONTHLY,
    WEEKLY: SUBSCRIPTIONS_PLANS_ANDROID.WEEKLY,
  },
  ios: {
    YEARLY: SUBSCRIPTIONS_PLANS_IOS.YEARLY,
    MONTHLY: SUBSCRIPTIONS_PLANS_IOS.MONTHLY,
    WEEKLY: SUBSCRIPTIONS_PLANS_IOS.WEEKLY,
  },
});
